//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mameui.rc
//
#define IDPAUSE                         3
#define IDS_UI_FILE                     61
#define IDS_UI_VIEW                     62
#define IDS_UI_OPTIONS                  63
#define IDS_UI_HELP                     64
#define IDS_VIEW_TOOLBAR                70
#define IDS_VIEW_STATUSBAR              71
#define IDS_VIEW_FOLDERLIST             72
#define IDS_VIEW_SCREENSHOT             73
#define IDS_VIEW_PICTURETABS            74
#define IDS_VIEW_SPACER1                75
#define IDS_VIEW_FULLSCREEN             76
#define IDS_VIEW_SPACER2                77
#define IDS_VIEW_SHOWPICTURES           78
#define IDS_VIEW_SPACER3                79
#define IDS_VIEW_LARGEICONS             80
#define IDS_VIEW_SMALLICONS             81
#define IDS_VIEW_LIST                   82
#define IDS_VIEW_DETAILS                83
#define IDS_VIEW_GROUPED                84
#define IDS_VIEW_SPACER4                85
#define IDS_VIEW_ARRANGE                86
#define IDS_VIEW_LINEUPICONS            87
#define IDS_VIEW_SPACER5                88
#define IDS_VIEW_REFRESH                89
#define IDS_VIEW_CONTEXTFILTERS         90
#define IDS_VIEW_CUSTOMIZEFIELDS        91
#define ID_TOOLBAR_EDIT                 92
#define IDI_MAMEUI                      100
#define IDI_WIN_ROMS                    101
#define IDI_WIN_NOROMS                  102
#define IDI_WIN_UNKNOWN                 103
#define IDI_WIN_CLONE                   104
#define IDI_WIN_REDX                    105
#define IDI_WIN_IMPERFECT               106
#define IDI_FOLDER                      107
#define IDI_FOLDER_ALLGAMES             108
#define IDI_FOLDER_AVAILABLE            109
#define IDI_FOLDER_BIOS                 110
#define IDI_FOLDER_CLONES               111
#define IDI_FOLDER_CPU                  112
#define IDI_FOLDER_DUMP                 113
#define IDI_FOLDER_FPS                  114
#define IDI_FOLDER_HARDDISK             115
#define IDI_FOLDER_HORIZONTAL           116
#define IDI_FOLDER_IMPERFECT            117
#define IDI_FOLDER_LIGHTGUN             118
#define IDI_FOLDER_MANUFACTURER         119
#define IDI_FOLDER_MECHANICAL           120
#define IDI_FOLDER_MONITOR              121
#define IDI_FOLDER_NONWORKING           122
#define IDI_FOLDER_OPEN                 123
#define IDI_FOLDER_ORIGINALS            124
#define IDI_FOLDER_RASTER               125
#define IDI_FOLDER_RESOL                126
#define IDI_FOLDER_SAMPLES              127
#define IDI_FOLDER_SAVESTATE            128
#define IDI_FOLDER_SOUND                129
#define IDI_FOLDER_SOURCE               130
#define IDI_FOLDER_TRACKBALL            131
#define IDI_FOLDER_UNAVAILABLE          132
#define IDI_FOLDER_VERTICAL             133
#define IDI_FOLDER_VECTOR               134
#define IDI_FOLDER_YEAR                 135
#define IDI_FOLDER_WORKING              136
#define IDI_BIOS                        137
#define IDI_CHIP                        138
#define IDI_CPU                         139
#define IDI_KEYBOARD                    140
#define IDI_MANUFACTURER                141
#define IDI_MONITOR                     142
#define IDI_SOURCE                      143
#define IDI_YEAR                        144
#define IDI_ADVANCED                    145
#define IDI_DISPLAY                     146
#define IDI_JOYSTICK                    147
#define IDI_MISC                        148
#define IDI_OPENGL                      149
#define IDI_SCREEN                      150
#define IDI_SHADER                      151
#define IDI_SNAPSHOT                    152
#define IDI_SOUND                       153
#define IDI_VECTOR                      154
#define IDI_CHECKMARK                   155
#define IDI_HEADER_UP                   156
#define IDI_HEADER_DOWN                 157
//#define IDI_AUDIT_PASS                  160
//#define IDI_AUDIT_FAIL                  161
//#define IDI_SYSTRAY                     162
//#define IDI_DISPLAYSHEET                163
//#define IDI_ADVANCEDSHEET               164
//#define IDI_SCREENSHEET                 165
//#define IDI_OPENGLSHEET                 166
//#define IDI_SHADERSHEET                 167
//#define IDI_VECTORSHEET                 168
//#define IDI_SOUNDSHEET                  169
//#define IDI_INPUTSHEET                  170
//#define IDI_CONTROLSHEET                171
//#define IDI_MISCSHEET                   172
//#define IDI_LUASHEET                    173
//#define IDI_SNAPSHEET                   174
#define IDI_WIN_NOROMSNEEDED            180
#define IDI_WIN_MISSINGOPTROM           181
#define IDI_WIN_FLOP                    182
#define IDI_WIN_CASS                    183
#define IDI_WIN_SERL                    184
#define IDI_WIN_SNAP                    185
#define IDI_WIN_PRIN                    186
#define IDI_WIN_HARD                    187
#define IDI_WIN_CYLN                    188
#define IDI_WIN_PTAP                    189
#define IDI_WIN_PCRD                    190
#define IDI_WIN_MIDI                    191
#define IDB_ABOUT                       200
#define IDB_TOOLBAR                     201
#define IDB_SPLASH                      202
#define IDB_ABOUTMENU                   214
#define IDB_CUSTOM                      215
#define IDB_DIRECTORIES                 216
#define IDB_EXIT                        217
#define IDB_FULLSCREEN                  218
#define IDB_INTERFACE                   219
#define IDB_HELP                        220
#define IDB_MAMEHOME                    221
#define IDB_PLAY                        222
#define IDB_PLAYM1                      223
#define IDB_OPTIONS                     224
#define IDB_REFRESH                     225
#define IDB_ZIP                         226
#define IDB_SAVELIST                    227
#define IDB_SAVEROMS                    228
#define IDB_PLAYBACK                    229
#define IDB_PROPERTIES                  230
#define IDB_AUDIT                       231
#define IDB_VIDEO                       232
#define IDB_FONTS                       233
#define IDB_FOLDERS                     234
#define IDB_SORT                        235
#define IDB_DRIVER                      236
#define IDB_FAQ                         237
#define IDB_TABS                        238
#define IDB_TROUBLE                     239
#define IDB_COUNT                       240
#define IDB_RELEASE                     241
#define IDB_TIME                        242
#define IDB_DESCRIPTION                 243
#define IDB_ROM                         244
#define IDB_SOURCE                      245
#define IDB_MANUFACTURER                246
#define IDB_YEAR                        247
#define IDB_PLAYWAV                     248
#define IDB_FONT1                       249
#define IDB_FONT2                       250
#define IDB_INFOBACK                    251
#define IDB_LISTBACK                    252
#define IDB_TREEBACK                    253
#define IDB_ASCENDING                   254
#define IDB_FIELDS                      255
#define IDB_RECAVI                      256
#define IDB_RECINPUT                    257
#define IDB_RECWAV                      258
#define IDB_PLAYMNG                     259
#define IDB_RANDOM                      260
#define IDB_RECMNG                      261
#define IDB_SAVESTATE                   262
#define IDB_FILTERS                     263
#define IDB_REMOVE                      264
#define IDB_RENAME                      265
#define IDB_RESET                       266
#define IDB_MANUAL                      270
#define IDB_NOTEPAD                     271
#define IDB_WEB_PAGE                    272
#define IDA_TAB_KEYS                    300
#define IDD_MAIN                        301
#define IDD_STARTUP                     302
#define IDD_ABOUT                       308
#define IDD_DIRECTX                     314
#define IDD_AUDIT                       315
#define IDD_DIRECTORIES                 316
#define IDD_CUSTOM_FILE                 317
#define IDD_PROP_GAME                   352
#define IDD_PROP_AUDIT                  353
#define IDD_PROP_DISPLAY                354
#define IDD_PROP_SOUND                  355
#define IDD_PROP_ADVANCED               356
#define IDD_PROP_INPUT                  357
#define IDD_PROP_MISC                   358
#define IDD_PROP_VECTOR                 359
#define IDD_COLUMNS                     360
#define IDD_FILTERS                     369
#define IDD_RESET                       370
#define IDD_LOAD_PROGRESS               371
#define IDD_INTERFACE_OPTIONS           373
#define IDD_PROP_CONTROLLER             385
#define IDD_PROP_SHADER                 386
#define IDD_PROP_SCREEN                 387
#define IDD_PROP_LUA                    389
#define IDD_PROP_OPENGL                 390
#define IDD_PROP_SNAP                   391
#define IDD_PROP_SOFTWARE               392
#define IDD_PROP_CONFIGURATION          393
#define IDR_MAIN_MENU                   400
#define IDR_UI_MENU                     401
#define IDR_CONTEXT_MENU                402
#define IDR_CONTEXT_HEADER              403
#define IDR_CONTEXT_TREE                404
#define IDR_CONTEXT_SCREENSHOT          405
#define IDC_CURSOR_HSPLIT               999
#define IDC_LIST                        1000
#define IDC_JOYSTICK                    1003
#define IDC_SIZES                       1005
#define IDC_FRAMESKIP                   1009
#define IDC_ROTATE                      1010
#define IDC_SCREEN                      1012
#define IDC_VIEW                        1013
#define IDC_SCREENSELECT                1014
#define IDC_CHEAT                       1015
#define IDC_LOG                         1016
#define IDC_ARTWORK_CROP                1017
#define IDC_ARTWORK_FALLBACK            1018
#define IDC_ARTWORK_OVERRIDE            1019
#define IDC_SLEEP                       1022
#define IDC_GAMMA                       1023
#define IDC_BRIGHTCORRECT               1024
#define IDC_USE_DEFAULT                 1025
#define IDC_CONTRAST                    1026
#define IDC_SAMPLERATE                  1027
#define IDC_NUMSCREENS                  1028
#define IDC_FLICKER                     1031
#define IDC_FLIPX                       1032
#define IDC_FLIPY                       1033
#define IDC_DIRECTX_HELP                1035
#define IDC_FLICKERDISP                 1036
#define IDC_FSCONTRAST                  1038
#define IDC_ROMS_PROGRESS               1039
#define IDC_SECONDSTORUN                1039
#define IDC_CONTRASTDISP                1040
#define IDC_ROMS_CORRECT                1041
#define IDC_FSCONTRASTDISP              1042
#define IDC_ROMS_INCORRECT              1043
#define IDC_SECONDSTORUNDISP            1043
#define IDC_NUMSCREENSDISP              1044
#define IDC_ROMS_TOTAL                  1045
#define IDC_SAMPLES_PROGRESS            1046
#define IDC_SAMPLES_CORRECT             1047
#define IDC_SAMPLES_INCORRECT           1049
#define IDC_SAMPLES_TOTAL               1050
#define IDC_AUDIT_DETAILS               1051
#define IDC_DIR_COMBO                   1053
#define IDC_DIR_LIST                    1054
#define IDC_DIR_BROWSE                  1055
#define IDC_DIR_INSERT                  1056
#define IDC_DIR_DELETE                  1057
#define IDC_SSFRAME                     1059
#define IDC_PRESCALE                    1060
#define IDC_SSPICTURE                   1062
#define IDC_MULTIKEYBOARD               1065
#define IDC_RATETEXT                    1069
#define IDC_LISTAVAILABLECOLUMNS        1070
#define IDC_LISTSHOWCOLUMNS             1071
#define IDC_BUTTONADD                   1072
#define IDC_BUTTONREMOVE                1073
#define IDC_BUTTONMOVEDOWN              1074
#define IDC_BUTTONMOVEUP                1075
#define IDC_PROP_SOUND                  1076
#define IDC_PROP_CPU                    1077
#define IDC_PROP_TITLE                  1078
#define IDC_PROP_MANUFACTURED           1079
#define IDC_PROP_STATUS                 1080
#define IDC_PROP_SCREEN                 1081
#define IDC_PROP_COLORS                 1082
#define IDC_PROP_ROMS                   1083
#define IDC_PROP_SAMPLES                1084
#define IDC_PROP_CLONEOF_TEXT           1085
#define IDC_PROP_CLONEOF                1086
#define IDC_VERSION                     1088
#define IDC_FSGAMMA                     1090
#define IDC_GAMMADISP                   1091
#define IDC_FSBRIGHTNESS                1092
#define IDC_FSGAMMADISP                 1093
#define IDC_PRESCALEDISP                1094
#define IDC_BRIGHTCORRECTDISP           1095
#define IDC_FSBRIGHTNESSDISP            1096
#define IDC_AUTOFRAMESKIP               1097
#define IDC_TREE                        1098
#define IDC_WINDOWED                    1099
#define IDC_PROP_RESET                  1101
#define IDC_SPLITTER                    1102
#define IDC_SPLITTER2                   1103
#define IDC_DIVIDER                     1104
#define IDC_FILTER_VECTOR               1105
#define IDC_FILTER_RASTER               1106
#define IDC_FILTER_UNAVAILABLE          1107
#define IDC_FILTER_NONWORKING           1108
#define IDC_FILTER_CLONES               1109
#define IDC_RESET_GAMES                 1110
#define IDC_RESET_UI                    1111
#define IDC_RESET_FILTERS               1112
#define IDC_RESET_EFFECT                1113
#define IDC_RESET_DEFAULT               1114
#define IDC_FILTER_ORIGINALS            1115
#define IDC_FILTER_WORKING              1116
#define IDC_FILTER_AVAILABLE            1117
#define IDC_FILTER_ARCADE               1118
#define IDC_FILTER_MESS                 1119
#define IDC_START_GAME_CHECK            1120
#define IDC_VOLUME                      1121
#define IDC_VOLUMEDISP                  1122
#define IDC_HISTORY                     1124
#define IDC_SAMPLES                     1125
#define IDC_TRIPLE_BUFFER               1127
#define IDC_LOAD_ROMNAME                1128
#define IDC_DEFAULT_INPUT               1129
#define IDC_LANGUAGECHECK               1130
#define IDC_LANGUAGEBROWSE              1131
#define IDC_LANGUAGEEDIT                1132
#define IDC_FILTER_EDIT                 1133
#define IDC_ABOUT                       1134
#define IDC_USE_SOUND                   1136
#define IDC_WAITVSYNC                   1137
#define IDC_SWITCHRES                   1139
#define IDC_MAXIMIZE                    1140
#define IDC_KEEPASPECT                  1141
#define IDC_SYNCREFRESH                 1142
#define IDC_USE_MOUSE                   1143
#define IDC_THROTTLE                    1144
#define IDC_VOLUMETEXT                  1146
#define IDC_REFRESH                     1148
#define IDC_REFRESHTEXT                 1149
#define IDC_EFFECT                      1150
#define IDC_FSGAMMATEXT                 1151
#define IDC_STEADYKEY                   1152
#define IDC_ASPECTRATION                1154
#define IDC_ASPECTRATIOD                1155
#define IDC_ASPECTRATIOTEXT             1156
#define IDC_JOY_GUI                     1157
#define IDC_BROADCAST                   1158
#define IDC_JDZ                         1159
#define IDC_JDZDISP                     1160
#define IDC_JDZTEXT                     1161
#define IDC_JSATTEXT                    1162
#define IDC_JSAT                        1163
#define IDC_JSATDISP                    1164
#define IDC_AUDIO_LATENCY_DISP          1165
#define IDC_PLAY_GAME                   1166
#define IDC_LIGHTGUN                    1167
#define IDC_SSTAB                       1168
#define IDC_GAME_ICON                   1169
#define IDC_RANDOM_BG                   1170
#define IDC_CUSTOM_TREE                 1171
#define IDC_CUSTOMFILE_GAME             1173
#define IDC_LOAD_STATUS                 1174
#define IDC_ERROR_TEXT                  1175
#define IDC_ARTMISCTEXT                 1176
#define IDC_ENABLE_AUTOSAVE             1177
#define IDC_SKIP_GAME_INFO              1178
#define IDC_PROP_SOURCE                 1179
#define IDC_FILTER_HORIZONTAL           1180
#define IDC_PAUSEBRIGHT                 1181
#define IDC_PAUSEBRIGHTDISP             1182
#define IDC_HIGH_PRIORITY               1183
#define IDC_D3D_FILTER                  1184
#define IDC_HIDE_MOUSE                  1185
#define IDC_AUDIO_LATENCY               1186
#define IDC_AUDIT_DETAILS_PROP0         1188
#define IDC_AUDIT_DETAILS_PROP1         1189
#define IDC_CYCLETIMESEC                1190
#define IDC_AUDIO_LATENCY_TEXT          1191
#define IDC_STRETCH_SCREENSHOT_LARGER   1192
#define IDC_FILTER_INHERIT              1193
#define IDC_RESET_PLAYSTATS             1194
#define IDC_INHERITED                   1196
#define IDC_KEY_GUI                     1197
#define IDC_RELOAD                      1198
#define IDC_DUAL_LIGHTGUN               1199
#define IDC_NOOFFSET_CLONES             1200
#define IDC_BIOS                        1201
#define IDC_HISTORY_TAB                 1202
#define IDC_SNAPVIEW                    1202
#define IDC_SCREENSHOT_BORDERSIZE       1204
#define IDC_SCREENSHOT_BORDERCOLOR      1205
#define IDC_CYCLETIMESECTXT             1206
#define IDC_SCREENSHOT_BORDERSIZETXT    1207
#define IDC_PADDLE                      1208
#define IDC_ADSTICK                     1209
#define IDC_PEDAL                       1210
#define IDC_DIAL                        1211
#define IDC_TRACKBALL                   1212
#define IDC_LIGHTGUNDEVICE              1213
#define IDC_MOUSE                       1214
#define IDC_POSITIONAL                  1215
#define IDC_HIGH_PRIORITY_TEXT          1216
#define IDC_HIGH_PRIORITYTXT            1217
#define IDC_SELECT_EFFECT               1218
#define IDC_MULTITHREAD_RENDERING       1219
#define IDC_ASPECT                      1220
#define IDC_LOAD_PROGRESS               1223
#define IDC_FSBRIGHTNESSTEXT            1224
#define IDC_FSCONTRASTTEXT              1225
#define IDC_VIDEO_MODE                  1226
#define IDC_SCREENSELECTTEXT            1227
#define IDC_PRESCALETEXT                1228
#define IDC_SOUND_MODE                  1229
#define IDC_MULTIMOUSE                  1230
#define IDC_REFRESHSPEED                1232
#define IDC_SPEEDTEXT                   1233
#define IDC_SPEED                       1234
#define IDC_SPEEDDISP                   1235
#define IDC_FILTER_VERTICAL             1236
#define IDC_SNAPNAME                    1237
#define IDC_COINLOCKOUT                 1238
#define IDC_SECONDSTORUNTEXT            1239
#define IDC_UPDATEINPAUSE               1242
#define IDC_RESET_JOYSTICKMAP           1247
#define IDC_JOYSTICKMAP                 1248
#define IDC_SNAPSIZE                    1249
#define IDC_SNAPSIZEWIDTH               1250
#define IDC_SNAPSIZEHEIGHT              1251
#define IDC_SNAPSIZETEXT                1252
#define IDC_SNAPSIZEX                   1253
#define IDC_FILTER_MECHANICAL           1254
#define IDC_LOWLATENCY                  1257
#define IDC_PROGBAR                     1265
#define IDC_SPLASH                      1266
#define IDC_HLSL_ON                     1279
#define IDC_SNAPBURNIN                  1280
#define IDC_PORTAUDIO_LATENCY           1281
#define IDC_PORTAUDIO_LATENCY_DISP      1282
#define IDC_GLSLPOW                     1300
#define IDC_GLSLTEXTURE                 1301
#define IDC_GLSLVBO                     1302
#define IDC_GLSLPBO                     1303
#define IDC_GLSL                        1304
#define IDC_GLSLFILTER                  1305
#define IDC_MAME_SHADER0                1306
#define IDC_MAME_SHADER1                1307
#define IDC_MAME_SHADER2                1308
#define IDC_MAME_SHADER3                1309
#define IDC_MAME_SHADER4                1310
#define IDC_SCREEN_SHADER0              1312
#define IDC_SCREEN_SHADER1              1313
#define IDC_SCREEN_SHADER2              1314
#define IDC_SCREEN_SHADER3              1315
#define IDC_SCREEN_SHADER4              1316
#define IDC_SELECT_SHADER0              1317
#define IDC_SELECT_SHADER1              1318
#define IDC_SELECT_SHADER2              1319
#define IDC_SELECT_SHADER3              1320
#define IDC_SELECT_SHADER4              1321
#define IDC_RESET_SHADER0               1322
#define IDC_RESET_SHADER1               1323
#define IDC_RESET_SHADER2               1324
#define IDC_RESET_SHADER3               1325
#define IDC_RESET_SHADER4               1326
#define IDC_SELECT_SCR_SHADER0          1327
#define IDC_SELECT_SCR_SHADER1          1328
#define IDC_SELECT_SCR_SHADER2          1329
#define IDC_SELECT_SCR_SHADER3          1330
#define IDC_SELECT_SCR_SHADER4          1331
#define IDC_RESET_SCR_SHADER0           1332
#define IDC_RESET_SCR_SHADER1           1333
#define IDC_RESET_SCR_SHADER2           1334
#define IDC_RESET_SCR_SHADER3           1335
#define IDC_RESET_SCR_SHADER4           1336
#define IDC_GLSLSYNC                    1337
#define IDC_EXIT_DIALOG                 1338
#define IDC_PROP_SAVESTATE              1339
#define IDC_DISPLAY_NO_ROMS             1340
#define IDC_DISABLE_TRAY_ICON           1341
#define IDC_CONFIRM_QUIT                1351
#define IDC_OVERRIDE_REDX               1352
#define IDC_SNAPBILINEAR                1353
#define IDC_BEAM_MIN                    1367
#define IDC_BEAM_MAX                    1368
#define IDC_BEAM_INTEN                  1369
#define IDC_BEAM_MINDISP                1370
#define IDC_BEAM_MAXDISP                1371
#define IDC_BEAM_INTENDISP              1372
#define IDC_BEAM_DOT                    1373
#define IDC_BEAM_DOTDISP                1374
#define IDC_EXIT_PLAYBACK               1379
#define IDC_LANGUAGE                    1380
#define IDC_UNEVENSTRETCH               1382
#define IDC_BOOTDELAY                   1383
#define IDC_BOOTDELAYDISP               1384
#define IDC_PLUGINS                     1386
#define IDC_PLUGIN                      1387
#define IDC_SELECT_PLUGIN               1388
#define IDC_RESET_PLUGIN                1389
#define IDC_BGFX_CHAINS                 1390
#define IDC_SELECT_BGFX                 1391
#define IDC_RESET_BGFX                  1392
#define IDC_UNEVENSTRETCHX              1393
#define IDC_INTOVERSCAN                 1394
#define IDC_INTSCALEX                   1395
#define IDC_INTSCALEY                   1396
#define IDC_INTSCALEX_TXT               1397
#define IDC_INTSCALEY_TXT               1398
#define IDC_UNEVENSTRETCHY              1399
#define IDC_AUTOSTRETCHXY               1400
#define IDC_NVRAM_SAVE                  1401
#define IDC_REWIND                      1402
#define IDC_AUTOBOOT_DELAY              1403
#define IDC_LUASCRIPT                   1404
#define IDC_SELECT_LUASCRIPT            1405
#define IDC_RESET_LUASCRIPT             1406
#define IDC_BGFX_BACKEND                1407
#define IDC_NATURAL                     1408
#define IDC_SAVE_INI                    1409
#define IDC_JOY_CONTRA                  1410
#define IDC_UI_SKIP_WARNINGS            1411
#define IDC_PROV_UIFONT                 1420
#define IDC_PROV_KEYBOARD               1421
#define IDC_PROV_MOUSE                  1422
#define IDC_PROV_LIGHTGUN               1423
#define IDC_PROV_JOYSTICK               1424
#define IDC_PROV_MONITOR                1425
#define IDC_PROV_OUTPUT                 1426
#define IDC_SPLITTER3                   2000
#define IDC_SWTAB                       2001
#define IDC_SWLIST                      2002
#define IDC_SWDEVVIEW                   2003
#define IDC_FILTER_COMPUTER             2004
#define IDC_FILTER_CONSOLE              2005
#define IDC_FILTER_MODIFIED             2006
#define IDC_RAM_COMBOBOX                2008
#define IDC_RAM_CAPTION                 2009
#define IDC_SOFTLIST                    2010
#define ID_MESS_OPEN_SOFTWARE           2200
// 3xxx reserved for NEWUI
#define ID_CONTEXT_SHOW_FOLDER_START    39000
#define ID_CONTEXT_SHOW_FOLDER_END      39200
#define ID_FILE_EXIT                    40001
#define ID_ABOUT                        40003
#define ID_FILE_PLAY                    40004
#define ID_HELP_ABOUT                   40006
#define ID_VIEW_LARGE_ICON              40007
#define ID_VIEW_SMALL_ICON              40008
#define ID_VIEW_LIST_MENU               40009
#define ID_VIEW_DETAIL                  40010
#define ID_VIEW_GROUPED                 40011
#define ID_OPTIONS_FONT                 40012
#define ID_OPTIONS_CLONE_COLOR          40013
#define ID_OPTIONS_DIR                  40014
#define ID_OPTIONS_DEFAULTS             40015
#define ID_OPTIONS_RESET_DEFAULTS       40016
#define ID_OPTIONS_INTERFACE            40017
#define ID_FILE_AUDIT                   40018
#define ID_FILE_PLAY_RECORD             40019
#define ID_FILE_PLAY_BACK               40020
#define ID_FILE_PLAY_RECORD_WAVE        40021
#define ID_FILE_PLAY_RECORD_MNG         40022
#define ID_FILE_PLAY_RECORD_AVI         40023
#define ID_VIEW_PICTURE_AREA            40024
#define ID_HELP_CONTENTS                40025
#define ID_HELP_WHATS_NEWUI             40026
#define ID_HELP_TROUBLE                 40027
#define ID_HELP_RELEASE                 40028
#define ID_HELP_WHATS_NEW               40029
#define ID_HELP_CHEATS                  40030
#define ID_FILE_AUDIT_X                 40031
#define ID_VIEW_BYGAME                  40034
#define ID_VIEW_BYDIRECTORY             40035
#define ID_VIEW_BYMANUFACTURER          40036
#define ID_VIEW_BYYEAR                  40037
#define ID_VIEW_BYTYPE                  40038
#define ID_VIEW_BYTIMESPLAYED           40039
#define ID_VIEW_LINEUPICONS             40040
#define ID_UPDATE_GAMELIST              40042
#define ID_UPDATE_CACHE                 40043
#define ID_SORT_ASCENDING               40045
#define ID_SORT_DESCENDING              40046
#define ID_CUSTOMIZE_FIELDS             40048
#define ID_GAME_PROPERTIES              40049
#define ID_VIEW_PAGETAB                 40050
#define ID_VIEW_FOLDERS                 40051
#define ID_VIEW_TOOLBARS                40052
#define ID_VIEW_STATUS                  40053
#define ID_CONTEXT_FILTERS              40054
#define ID_CONTEXT_RENAME_CUSTOM        40055
#define ID_CONTEXT_ADD_CUSTOM           40057
#define ID_CONTEXT_REMOVE_CUSTOM        40058
#define ID_GAME_AUDIT                   40059
#define ID_CONTEXT_SELECT_RANDOM        40060
#define ID_OPTIONS_BG                   40070
#define ID_VIEW_FULLSCREEN              40079
#define ID_CONTEXT_RESET_PLAYSTATS      40081
#define ID_FOLDER_PROPERTIES            40082
#define ID_FOLDER_AUDIT                 40083
#define ID_UI_UP                        40084
#define ID_UI_DOWN                      40085
#define ID_UI_LEFT                      40086
#define ID_UI_RIGHT                     40087
#define ID_UI_START                     40088
#define ID_UI_PGUP                      40089
#define ID_UI_PGDOWN                    40090
#define ID_UI_HOME                      40091
#define ID_UI_END                       40092
#define ID_UI_HISTORY_UP                40093
#define ID_UI_HISTORY_DOWN              40094
#define ID_FILE_LOADSTATE               40095
#define ID_FOLDER_SOURCEPROPERTIES      40096
#define ID_FOLDER_VECTORPROPERTIES      40097
#define ID_OPTIONS_MAMEINFO             40100
#define ID_OPTIONS_HISTORY              40101
#define ID_VIEW_SOFTWARE_AREA           40102
#define ID_MANUAL                       40108
#define ID_VIDEO_SNAP                   40109
#define ID_PLAY_VIDEO                   40110
#define ID_PLAY_AUDIO                   40111
#define ID_PLAY_MNG                     40112
#define ID_PLAY_M1                      40113
#define ID_NOTEPAD                      40114
#define ID_RC_CLEAN                     40115
#define ID_VIEW_TAB_ARTWORK             40120
#define ID_VIEW_TAB_BOSSES              40121
#define ID_VIEW_TAB_CABINET             40122
#define ID_VIEW_TAB_CONTROL_PANEL       40123
#define ID_VIEW_TAB_COVER               40124
#define ID_VIEW_TAB_ENDS                40125
#define ID_VIEW_TAB_FLYER               40126
#define ID_VIEW_TAB_GAMEOVER            40127
#define ID_VIEW_TAB_HOWTO               40128
#define ID_VIEW_TAB_LOGO                40129
#define ID_VIEW_TAB_MARQUEE             40130
#define ID_VIEW_TAB_PCB                 40131
#define ID_VIEW_TAB_SCORES              40132
#define ID_VIEW_TAB_SELECT              40133
#define ID_VIEW_TAB_SCREENSHOT          40134
#define ID_VIEW_TAB_TITLE               40135
#define ID_VIEW_TAB_VERSUS              40136
#define ID_VIEW_TAB_HISTORY             40137
#define ID_TOGGLE_TAB_ARTWORK           40150
#define ID_TOGGLE_TAB_BOSSES            40151
#define ID_TOGGLE_TAB_CABINET           40152
#define ID_TOGGLE_TAB_CONTROL_PANEL     40153
#define ID_TOGGLE_TAB_COVER             40154
#define ID_TOGGLE_TAB_ENDS              40155
#define ID_TOGGLE_TAB_FLYER             40156
#define ID_TOGGLE_TAB_GAMEOVER          40157
#define ID_TOGGLE_TAB_HOWTO             40158
#define ID_TOGGLE_TAB_LOGO              40159
#define ID_TOGGLE_TAB_MARQUEE           40160
#define ID_TOGGLE_TAB_PCB               40161
#define ID_TOGGLE_TAB_SCORES            40162
#define ID_TOGGLE_TAB_SELECT            40163
#define ID_TOGGLE_TAB_SCREENSHOT        40164
#define ID_TOGGLE_TAB_TITLE             40165
#define ID_TOGGLE_TAB_VERSUS            40166
#define ID_TOGGLE_TAB_HISTORY           40167
#define IDC_STATIC                      -1

